// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRKZpvWJ3Z35Pme7Io_uy57lhVTKzzbAA',
    appId: '1:666909682385:web:01b66fc9a492e6f0e033f0',
    messagingSenderId: '666909682385',
    projectId: 'adminitradorit',
    authDomain: 'adminitradorit.firebaseapp.com',
    storageBucket: 'adminitradorit.appspot.com',
    measurementId: 'G-C8NM43RLG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkgffh7KhxzqMzIZNx_trb5kj5aExwcQ',
    appId: '1:666909682385:android:92e3b1271ff5763ce033f0',
    messagingSenderId: '666909682385',
    projectId: 'adminitradorit',
    storageBucket: 'adminitradorit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fJHz9ZQy4I8mHObTTDIceWbZx08FXZM',
    appId: '1:666909682385:ios:03d1a58d80dec01ce033f0',
    messagingSenderId: '666909682385',
    projectId: 'adminitradorit',
    storageBucket: 'adminitradorit.appspot.com',
    iosClientId: '666909682385-7jtpnudjkuc2mprisnrnb4v1arpfbk0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.itadministrador',
  );
}
